language: java

jobs:
  include:
    - if: 'branch = features'
      os: linux
      jdk: openjdk8
      addons:
        apt:
          packages:
            - openjfx
            - graphviz
      before_script:
        - 'git checkout -b master'
        - 'git rebase features'
      after_success:
        - './build_docs.sh'
        - 'git add docs'
        - 'git commit -m "commit docs"'
        - 'git status'
        - 'git remote add authd https://cmosher01:$GITHUB_TOKEN@github.com/cmosher01/Afl2.git'
        - 'git push authd master'
    - if: 'tag =~ /^v\d/'
      os: linux
      jdk: openjdk8
      addons:
        apt:
          packages:
            - openjfx
            - rpm
            - fakeroot
      script:
        - ./gradlew jfxNative
        - ls -l build/jfx/native
      deploy:
        provider: releases
        api_key:
          secure: $GITHUB_TOKEN
        file_glob: true
        file:
          - 'build/jfx/native/*.deb'
          - 'build/jfx/native/*.rpm'
        skip_cleanup: true
        on:
          tags: true
    - if: 'tag =~ /^v\d/'
      os: osx
      osx_image: xcode9.3
      script:
        - ./gradlew jfxNative
        - ls -l build/jfx/native
      deploy:
        provider: releases
        api_key:
          secure: $GITHUB_TOKEN
        file_glob: true
        file:
          - 'build/jfx/native/*.pkg'
        skip_cleanup: true
        on:
          tags: true
